sudo: false
env: RELEASE_TESTING=1
dist: trusty
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpanm --quiet --notest Dancer Dancer2 Test::CheckManifest Test::Spelling Pod::Coverage Test::Pod::Coverage
  - cpanm --quiet --installdeps --notest .
